# usage :
#
#   ``bash
#   # create an external public network 
#   docker network create traefik-public
#   # compose containers
#   docker-compose up  
#   ```
# 
#   Open swagger ui in Chrome or Vivaldi browser http://web.service.localhost/docs. 
#   Currently does not work in firefox and safari.

services:
  reverse-proxy:
    image: traefik:v2.4 # build container from this image
    container_name: reverse-proxy
    command: 
      # Traefik will listen on port 8080 by default for API request
      - "--api.insecure=true"  # NOT RECOMMENDED FOR PRODUCTION
      - "--providers.docker"
      # do not expose all docker services, only the ones specified
      - "--providers.docker.exposedbydefault=false" # don't expose every container to traefik, only enabled ones
      - "--entrypoints.http.address=:80"
    ports:
      # local machine port : container port
      - 80:80       # default http ports
      - 443:443     # default https ports
      - 8080:8080   # default traefik dashboard
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public      
    volumes:
      # Add Docker as a mounted volume, so that 
      # Traefik can communicate w/ it
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - traefik-public

  # model service
  model-service:
    image: x86_64/convnet-model-service:0.8.1
    container_name: model-service
    environment: # set environment variable in container
      MODEL_NAME: model
    networks:
      - traefik-public

  # web service
  web-service:
    image: x86_64/convnet-web-service:0.8.1
    container_name: web-service
    environment:
      SERVING_SERVICE: model-service
    labels:
      - traefik.enable=true
      # specify host to search in web browser
      - traefik.http.routers.web-service.rule=Host(`web.service.localhost`)
    networks:
      - traefik-public
      
networks:
  traefik-public:
    external: true
