
# author: steeve laquitaine
#
# usage:
#
#   ```bash
#   # run in codebase's root
#   docker_web/build.sh
#   ```

FROM python:3.7
RUN pip install --upgrade pip
WORKDIR /code
COPY docker_web/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
CMD ["python", "-u", "web_app.py"]