# Set hyperparameters
EPOCHS: 1
VERSION: 1 # (int)
LABELS: ["T-shirt/top","trouser", "pullover", "Dress", 
                "coat", "Sandal", "Shirt","Sneaker", "Bag", "Ankle boot"]

MODEL_LOSS: "sparse_categorical_crossentropy"
METRICS: ["accuracy"]

# set storage path
MODEL_PATH: ./models/model/

# model
MODEL_NAME: convnet

# Server HOST
HOST: http://localhost

# Server PORT
PORT: 8502