# author: steeve laquitaine
# usage: 
#   conda env create -f src/environment.yml # creates my_env

name: convnet
dependencies:
  - python #=3.7
  - tensorflow #=2.6.0
  - matplotlib
  - pip:
    - black
    - pylint