# author: steeve laquitaine
# usage: 
#   conda env create -f src/environment.yml # creates my_env

name: convnet
dependencies:
  - python      #=3.7
  - tensorflow  #=2.6.0
  - matplotlib  #==3.3.4
  - ipykernel   #==6.4.1
  - pyyaml      #=5.4.1
  - jinja2      #=3.0.1 # web page templating
  - pip:
    - black     #=21.9b0
    - pylint
    - fastapi   #=0.70.0
    - uvicorn[standard] #=0.15.0
    - pyngrok   #5.1.0
    - nest-asyncio #=1.5.1